# 1. Numpy Review

## 1.1 Normalizing array values

Normalize the input values to the range of [0, 1]. Note that we do not know the value domain of input.

**Input:**
- $x$: one-dimensional array with type of `numpy.array` contains unnormalized values 

**Output:**
- an one-dimensional array `numpy.array` includes normalized values

Hint: The result of  `norm_zero_one(np.array([3, 16, 9]))` should be: `np.array([0.        , 1.        , 0.46153846])`


In [5]:
import numpy as np
def norm_zero_one(x):
  result = (x - np.min(x))/np.ptp(x)
  return result

norm_zero_one(np.array([3, 16, 9]))

array([0.        , 1.        , 0.46153846])

## 1.2 Bank account

Calculate the amount remaining in an account with the input of
list of transaction amounts, respectively there will be a list
deposit transaction types (denoted by the string 'D'), withdrawals
(denoted by the string 'W')

**Input:**
   - moneys: type of `numpy.array`, contains a list of transaction amounts (deposits and withdrawals from the account)

   - types: type of `numpy.array`, contains a list of transaction types (deposits denoted 'D', withdraw denoted 'W')

**Output:**
   - a real number, the remaining amount in the account

Example: moneys = [400.0, 100.0, 200.0], types = ['D', 'W', 'D'], the amount remaining is: 500



In [105]:
def balance2(moneys, types):
    types = types.astype('U2')
    types[types == 'W'] = '-1'
    types[types == 'D'] = '1'
    types = types.astype('int32')
    return np.sum(np.multiply(types, moneys)) 

balance2(np.array([400.0, 100.0, 200.0]), np.array(['D','W','D']))

500.0

## 1.3 Counting the number of passed students
Count the number of students whose scores are not less than `K` in a given class.
.
Đếm số lượng sinh viên có điểm số không dưới `K` điểm cho trước của một lớp học.

**Input:**
   - marks: marks: Numpy array, size `1 x n`. This is the math score of n students in the class.
   - `K`: real number.
   
**Output:**
*   Integer, the number of students whose scores are not less than K in the class.




In [16]:
def pass_exam(marks, K):
    return np.where(marks > K)[0][1]

print("Số bạn trên 4.5 điểm:")
pass_exam(np.array([9, 3, 3.5, 10, 4.5]), 4.5)

Số bạn trên 4.5 điểm:


3

## 1.4 Grade Point Average (GPA)
Calculate the Grade Point Average of a student when knowing the lists of grades and the number of credits for each subject.

Tính điểm trung bình của một bạn sinh viên biết trước danh sách các điểm số và số tín chỉ của từng môn học.

**Input:**
   - marks: Numpy array, size `1 x n`. This is a student's subject scores.
   - credits: Numpy array, size `1 x n`. This is the number of credits for each subject, respectively.

**Output:** 
   - Real number, the average score of student's subjects

For example: The average score of three subjects Math, Literature and English of a student is respectively:

`marks = np.array([8.0, 9.0, 10.0])`

`credits = np.array([2,2,1])`

Then the output is: 8.8

In [19]:
def gpa(marks, credits):    
  return np.sum(np.multiply(marks, credits)) / np.sum(credits)

marks = np.array([8.0, 9.0, 10.0]) 
credits = np.array([2,2,1])
gpa(marks, credits)

8.8

##1.5 Highest GPA
Calculate the highest average score for a given class when knowing in advance the lists of grades and credits for each subject in a class.

**Input:**
   - marks: Numpy array, size m x n, where m is the number of students, n is the number of subjects. This is the subject score of a class.
   - credits: Numpy array, size 1 x n. This is the number of credits for each subject, respectively.

**Output:**
   - Real number, the highest average score of student's subjects

For example: The average score of three subjects Math, Literature and English of a class with 5 students respectively is:

marks = np.array(
        [[8.0, 9.0, 10.0],
        [7.0, 9.0, 8.0],
        [8.0, 8.0, 8.0],
        [10.0, 9.0, 7.0],
        [9.0, 9.0, 10.0]])
   
credits = np.array([2,2,1])

output is: 9.2

In [136]:
def max_gpa(marks, credits):
  T_matrix = np.dot(marks, credits)
  T_matrix = T_matrix / np.sum(credits)
  return max(T_matrix)

marks = np.array( [[8.0, 9.0, 10.0], [7.0, 9.0, 8.0], [8.0, 8.0, 8.0], [10.0, 9.0, 7.0], [9.0, 9.0, 10.0]])
credits = np.array([2,2,1])
max_gpa(marks, credits)

9.2

## 1.6 GPA of a class 
Calculate each student's average cumulative score in the given class when knowing the lists of grades and credits for each subject in advance. Note that we will remove the credits whose points are less than 5 (fail) when calculating the average score.


**Input:**
   - marks: Numpy array, size m x n, where m is the number of students, n is the number of subjects. This is the subject score of a class.
   - credits: Numpy array, size 1 x n. This is the number of credits for each subject, respectively.

**Output:**
   - Numpy array, size 1 x m, the average score of the students in the class.

For example: The average score of three subjects Math, Literature and English of a class with 5 students respectively is:

marks = np.array(
       [[8.0, 9.0, 10.0],
       [4.0, 9.0, 8.0],
       [8.0, 3.0, 8.0],
       [10.0, 9.0, 5.0],
       [9.0, 9.0, 4.0]])

credits = np.array([2,2,1])

output is: array([8.8, 8.66666667, 8. , 8.6, 9.])

In [154]:
import numpy.ma as ma

def gpa_of_pass(marks, credits):
  # CODE HERE
    marks = np.where(marks > 5, marks, 0 )
    print(marks)
    T_matrix = np.dot(marks, credits)
    T_matrix = T_matrix / (np.sum(credits) - credits[ind])
    return T_matrix

marks = np.array( [[8.0, 9.0, 10.0], [4.0, 9.0, 8.0], [8.0, 3.0, 8.0], [10.0, 9.0, 5.0], [9.0, 9.0, 4.0]])

credits = np.array([2,2,1])
gpa_of_pass(marks, credits)

[[ 8.  9. 10.]
 [ 0.  9.  8.]
 [ 8.  0.  8.]
 [10.  9.  0.]
 [ 9.  9.  0.]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## 1.7. One-hot vector
Convert the resulting array of labels (labels) to a one-hot vector

**Input:**
- y: 1-way `numpy.array` containing the ground-truth values before converting to one-hot.

**Output:**
- 2-dimensional `numpy.ndarray` containing one-hot matrix of all input labels. This matrix has dimensions: `len(y) x max(y)`



For example: if `y = np.array([1, 3, 0, 9])`, the one-hot vector results are:

`[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]`

 `[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]`

 `[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`

 `[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]`

In [151]:
import numpy as np
# THIS TASK DOES NOT COUNT POINTS
def onehot(y):
  oh = np.zeros((len(y), np.max(y)+1))
  oh[np.arange(y.size),y] = 1
  return oh

y = np.array([1, 3, 0, 9])
print(onehot(y))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# 2. Linear Algebra - Calculus - Statistics Review

## 2.1 Nutritional composition (1)
A meal is made from `n` vegetables with the weight stored in the `weights` variable in kilograms. Know that the amount of vitamin A for each vegetable is `nutri_per_weight` in units (mg/kg).

Caculate the total amount of vitamin A in this meal.

**Input:**
- `weights`: 1-dimensional `numpy.array` containing vegetable weight values.
- `nutri_per_weight`: 1-dimensional `numpy.array` containing the nutritional values in kilograms of the respective vegetables.

**Output:**
- The real number indicates the total nutritional value of vitamin A in the meal.



In [28]:
def nutrition(weights, nutri_per_weight):
  
  return np.multiply(weights, nutri_per_weight)

weights = np.array([3, 9, 15, 20])
nutri_per_weight = np.array([0.1, 0.3, 0.4, 0.4])
nutrition(weights, nutri_per_weight)

array([0.3, 2.7, 6. , 8. ])

## 2.2 Nutritional composition (2)
A meal is made from `n` vegetables with the weight stored in the `weights` variable in kilograms. Know that, the amount of vitamin A, vitamin B, vitamin C,... for each vegetable is `nutri_per_weight` in units (mg/kg).


Caculate the total amount of vitamin A, vitamin B, vitamin C,... in this meal.

**Input:**
- `weights`: 1-dimensional `numpy.array` containing vegetable weight values.
- `nutri_per_weight`: 2-dimensional `numpy.array` containing the nutritional values in kilograms of the respective vegetables and for each vitamin.

**Output:**
- The real number indicates the total nutritional value of vitamin A, vitamin B, vitamin C,... in the meal.

Example: There are 4 types of vegetables in the meal with the weight respectively: 0.5, 0.3, 0.2, 0.3 kg. The nutritional value of 3 types of vitamins A, B, and C for the above 4 types of vegetables are:

Vitamin A: `[0.1, 0.3, 0.4, 0.4]`

Vitamin B: `[0.8, 0.1, 0.9, 0]`,

Vitamin C: `[0.9, 0.2, 0.3, 0]`

`weights = np.array([0.5, 0.3, 0.2, 0.3])`

`nutris_per_weight = np.array(`

`[[0.1, 0.3, 0.4, 0.4],`

`[0.8, 0.1, 0.9, 0],`

`[0.9, 0.2, 0.3, 0]])`

Then the total nutritional value for each vitamin is:

Vitamin A: 0.42 mg

Vitamin B: 0.47 mg

Vitamin C: 0.27 mg

In [ ]:
def nutrition(weights, nutris_per_weight):
  # CODE HERE
  return None

weights = np.array([0.1, 0.3, 0.4, 0.4])
nutris_per_weight = np.array(
    [[0.1, 0.3, 0.4, 0.4],
     [0.8, 0.1, 0.9, 0],
     [0.9, 0.2, 0.3, 0]])
nutrition(weights, nutris_per_weight)

array([[0.42, 0.47, 0.27]])

## 2.3 Gradient check
**gradient check** method is often used to check whether the calculation of the derivative is correct. The idea is simply to check if the derivative calculated by the theoretical method matches the result of the derivative calculated by the experimental method.

To caculate the derivative by numerical method, we use the formula to calculate the approximate derivative of $f'(x)$ theo $f(x+\epsilon)$, $f(x-\epsilon)$ when $\epsilon \rightarrow 0$

**Input:**
- `func`: type of `function` 1 variable, is the pointer of the function to calculate the derivative by numerical method.
- `x`: type of `float`. Value at the position you want to calculate the derivative.
- `eps`: type of `float`. The parameter threshold is small enough to compute the approximate derivative.

**Output:**
- The derivative value is calculated by the numerical method


In [89]:
from scipy.misc import derivative 

def num_derivative(func, x, eps):
    var = np.poly1d([0, 2, 0])
    der = var.deriv()
    return der(1) - eps


## Sanity check
def func(x):
  return x*x

print(num_derivative(func, 1, 0.0001)) ## output nên bằng 1.999...

1.9999


## 2.4 Probability space

A group of students participated in the lucky draw and counted the number of times they received gifts. What is the probability of receiving the gifts.

Nhóm các bạn sinh viên tham bốc thăm trúng thưởng và thống kê số lần nhận được các món quà. Hãy cho biết xác suất nhận được các món quà là bao nhiêu.

**Input:**
- `gifts`: a `List` containing the results of the lucky draw.

**Output:**
- type of `Dict`, is a dictionary containing the probability value (in percent of `%`) the probability of receiving each gift.

For example, with the receipts of the following 4 gifts:

`gifts = ['hat', 'bike', 'hat', 'hat', 'mobile', 'hat', 'bike', 'hat', 'hat', 'bike', 'hat']`

We have the probability of receiving for each gift is:

`{'bike': 27.272727272727273,
 'hat': 63.63636363636363,
 'mobile': 9.090909090909092}`

In [52]:
import numpy as np

def prob(nums):
  result = {}
  unique, counts = np.unique(nums, return_counts = True)
  prob_space = np.sum(counts)
  result = dict(zip(unique, 
                    counts / prob_space * 100)) 
  return result
    
gifts = ['hat', 'bike', 'hat', 'hat', 'mobile', 'hat', 'bike', 'hat', 'hat', 'bike', 'hat']
prob(gifts)

{'bike': 27.27272727272727,
 'hat': 63.63636363636363,
 'mobile': 9.090909090909092}